# Generated by Django 3.1.1 on 2020-09-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200909_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_state',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sports Wear'), ('OW', 'Outwear')], default='N', max_length=2),
        ),
    ]
