# Generated by Django 3.1.1 on 2020-09-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200909_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'BestSeller'), ('B', 'Best')], default='N', max_length=2),
        ),
    ]
