# Generated by Django 3.1.1 on 2020-09-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
